baseurl = "http://traviskn.github.io/"
languageCode = "en-us"
title = "Travis Nuttall's Blog"
theme = "hugo_theme_travis"
canonifyurls = true
pygmentsstyle = "default"
PygmentsCodeFences = true

[taxonomies]
  tag = "tags"
  series = "series"

[Params]
  Author = "Travis Nuttall"
